document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("	<meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("	<title>Document</title>");
document.writeln("	<link rel=\'stylesheet\' href=\'/css/header.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("	<div class=\'header\'>");
document.writeln("");
document.writeln("		<a href=\'javascript:;\' class=\'diYi\'>小米商城</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>MIUI</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>IoT</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>云服务</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>金融</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>有品</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>小爱开放平台</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>企业团购</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>资质证照</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>协议规则</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>下载app</a>");
document.writeln("		<span class=\'sep\'>|</span>");
document.writeln("		<a href=\'javascript:;\'>Select Region</a>");
document.writeln("");
document.writeln("		<div class=\'rightBox\'>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'javascript:;\'>登录</a></li>");
document.writeln("				<span class=\'sep\'>|</span>");
document.writeln("				<li><a href=\'javascript:;\'>注册</a></li>");
document.writeln("				<span class=\'sep\'>|</span>");
document.writeln("				<li><a href=\'javascript:;\'>消息通知</a></li>");
document.writeln("				<li><a href=\'javascript:;\'> 购物车</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	</div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");